---
language: python
python: '2.7'
sudo: required
addons:
  apt:
    sources:
      - python-apt
      - python-pycurl
matrix:
  - install:
    - pip install --upgrade pip
    - pip install "ansible>=1.9,<2.0"
  - install:
    - pip install --upgrade pip
    - pip install "ansible>=2.0"
env:
  global:
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local

script:
  - ansible-playbook --syntax-check -i test/inventory test/playbook.yml
  - ansible-playbook -i test/inventory test/playbook.yml --connection=local –b -vvvv
...
