---
# tasks file for ansible-hosts

- name: Update hosts file
  template:
    dest: "{{ hosts_file_path }}"
    src: "{{ hosts_file_template }}"
    backup: "{{ hosts_file_backup }}"
    owner: "{{ hosts_file_owner | default(omit) }}"
    group: "{{ hosts_file_group | default(omit) }}"
    mode: "{{ hosts_file_mode | default(omit) }}"

...
